In [ ]:
#Create an array of numbers from one to twenty in reverse order.

import numpy as np
numbers=np.arange(20,0,-1)
print(numbers)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [ ]:
#Create an array of 10 numbers which is evenly spaced in the range of 1 to 5.

import numpy as np
numbers=np.linspace(1,5,10)
print(numbers)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
#Create an array of 10 numbers which is evenly spaced in the range of 1 to 5 on log scale.

import numpy as np
numb=np.logspace(1,5,10)
print(numb)

[1.00000000e+01 2.78255940e+01 7.74263683e+01 2.15443469e+02
 5.99484250e+02 1.66810054e+03 4.64158883e+03 1.29154967e+04
 3.59381366e+04 1.00000000e+05]


In [ ]:
#Create an array of 10 random numbers in the range of 200 to 300.

import numpy as np
numbers=np.random.randint(200,300,10)
print(numbers)

[239 285 268 245 262 200 252 266 290 291]


In [ ]:
#Create a 2D array of size 2X3 with all elements filled with 8
a1=np.full((2,3),8)
a1

array([[8, 8, 8],
       [8, 8, 8]])

In [ ]:
# Create a 2D array of size 4X3 with all elements in the range of 1 to 12 and perform following operations:
#Display the created array.
a2=np.arange(1,13)
a2=a2.reshape(4,3)
a2


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#Display the second row of the created array.

a2[1]

array([4, 5, 6])

In [ ]:
#Display the second column of the created array.

a2[:,1]

array([ 2,  5,  8, 11])

In [ ]:
#Display alternate columns of the created array.

a2[:,::2]

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [ ]:
#Display second and fourth row of the created array

a2[1::2,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
#Display odd rows and even column.

a2[0::2,1::2]

array([[2],
       [8]])

In [ ]:
#Write a Python program to generate a 1-D array containing 100 values, where each value hasto be 10, 20, 50 or 75.
#The probability for the value to be 10 is set to be 0.4
#The probability for the value to be 20 is set to be 0.2
#The probability for the value to be 50 is set to be 0.1
#The probability for the value to be 75 is set to be 0.3

a3=np.random.choice((10,20,50,75),100,p=[0.4,0.2,0.1,0.3])
a3

array([75, 10, 10, 20, 20, 20, 20, 10, 20, 10, 75, 75, 10, 10, 75, 10, 10,
       20, 10, 10, 10, 20, 75, 10, 10, 50, 20, 20, 75, 75, 50, 10, 10, 10,
       75, 75, 50, 75, 75, 10, 10, 20, 20, 75, 20, 10, 75, 75, 10, 20, 75,
       50, 20, 50, 75, 75, 75, 10, 10, 10, 75, 75, 20, 75, 75, 20, 50, 10,
       10, 50, 10, 20, 75, 10, 10, 10, 10, 10, 10, 75, 10, 20, 20, 75, 75,
       10, 20, 10, 10, 20, 50, 10, 10, 10, 75, 20, 10, 20, 10, 75])